# Module: docker
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.16/metricbeat-module-docker.html

- module: docker
  metricsets:
    - container
    - memory
    - cpu
    - info
  period: 30s
  hosts: ["unix:///var/run/docker.sock"]